### ISSUE TITLE
htmlstatus parameter doesn't work

### ISSUE THREAD

**Issue by kenrestivo** [redmatrix/hubzilla#104]
The docs say:

```
status: the content of the posting, formatted with BBCode
                                OR
htmlstatus:the content of the posting, formatted in HTML.
```

Tried this
```sh
curl  -u testing:test  -d "htmlstatus=foobar" -d "title=atitle"  http://hubzilla/api/statuses/update
```

Got this:
```
2015-10-28 04:01:33:d0kauatbrf5sbhhgppqsddoc74 api.php:93:api_login: /home/src/hubzilla/include/api.php93api_login
exception 'OAuthException' with message 'Invalid consumer key' in /home/src/hubzilla/library/OAuth1.php:610
Stack trace:
#0 /home/src/hubzilla/library/OAuth1.php(556): OAuthServer->get_consumer(Object(OAuthRequest))
#1 /home/src/hubzilla/include/api.php(78): OAuthServer->verify_request(Object(OAuthRequest))
#2 /home/src/hubzilla/include/api.php(174): api_login(Object(App))
#3 /home/src/hubzilla/mod/api.php(114): api_call(Object(App))
#4 /home/src/hubzilla/index.php(339): api_content(Object(App))
#5 {main}
2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 auth.php:77:account_verify_password: password verified for test@test.com
2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 api.php:181:api_call: API call for testing: api/statuses/update
2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 api.php:182:api_call: API parameters: Array
(
    [q] => api/statuses/update
    [htmlstatus] => foobar
    [title] => atitle
)

2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 api.php:809:api_statuses_update: api_statuses_update: REQUEST Array
(
    [q] => api/statuses/update
    [htmlstatus] => foobar
    [title] => atitle
)

2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 api.php:810:api_statuses_update: api_statuses_update: FILES Array
(
)

2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 api.php:327:api_get_user: api_user:  AND abook_channel = %d AND abook_self = 1 , user: 5
2015-10-28 04:01:33:eivdg45mc36lj9hognmqg1jj84 item.php:290:item_post: mod_item: post accepted from testing for testing

```

And it silently failed to post, returned blank data. 

But, the same command with status instead of htmlstatus worked fine. This is reproducible.

If I can fix this I will, but I'm kind of baffled by all the oauth setup in here, and that stacktrace worries me, so if I could punt this I'd prefer to do so.

**Comment by redmatrix** [comment]
We always check for OAuth, even when handed a password. 

I'll have a look at the htmlstatus part.

**Comment by redmatrix** [comment]
should be fixed

**Comment by kenrestivo** [comment]
Thanks, that was it. For testing I was just giving it some text without tags. Very much an edge case.

Would it make sense for API calls that fail to return a 500 error and maybe even informative error message, rather than just 200'ing and silently returning an empty body?
