### ISSUE TITLE
PHP fatal error: call to undefined function photo_calculate_scale()

### ISSUE THREAD

**Issue by hethi** [redmatrix/hubzilla#1201]
Just tried to change a cover photo of a channel and got this error output in php.out, and a white screen:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Zotlabs\Module\photo_calculate_scale() in /var/www/hubzilla/Zotlabs/Module/Cover_photo.php:96
Stack trace:
#0 /var/www/hubzilla/Zotlabs/Web/Router.php(255): Zotlabs\Module\Cover_photo->post()
#1 /var/www/hubzilla/Zotlabs/Web/WebServer.php(115): Zotlabs\Web\Router->Dispatch()
#2 /var/www/hubzilla/index.php(14): Zotlabs\Web\WebServer->run()
#3 {main}
  thrown in /var/www/hubzilla/Zotlabs/Module/Cover_photo.php on line 96
```

I'm running hubzilla on dev branch,
```
$ git describe --tags
1.8-4705-g33700e9
```

**Comment by hethi** [comment]
Adding an `require_once` helped:
```
diff --git a/Zotlabs/Module/Cover_photo.php b/Zotlabs/Module/Cover_photo.php
index 9adfa22..88fd448 100644
--- a/Zotlabs/Module/Cover_photo.php
+++ b/Zotlabs/Module/Cover_photo.php
@@ -9,6 +9,7 @@ namespace Zotlabs\Module;
 
 require_once('include/photo/photo_driver.php');
 require_once('include/channel.php');
+require_once('include/photos.php');
 
 
 

```

**Comment by zotlabs** [comment]
Thanks. I assumed that was already included in any controller that dealt with photos, but in retrospect that was a bad assumption.
