### ISSUE TITLE
2016-03-26.1347H Fatal error:  Uncaught Error in Cron 

### ISSUE THREAD

**Issue by royalterra** [redmatrix/hubzilla#335]
This can be a simple bad error of configuration in the php.ini BUT I already tested with 3 hubs in one server the error reproduce only in version : 2016-03-26.1347H - 1165  but I can't reproduce in any version like 2016-03-17.1338H - 1165 I can confirm php5 Mysql work perfect but fail in CLI I try php5-mysql and php5-mysqlnd not make difference the errors reproduce in the new Hubzilla Version
**
Error with command cd /var/www/domain; /usr/bin/php include/poller.php**

```
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/domain/include/dba/dba_mysql.php:9     

Stack trace:
#0 /var/www/domain/include/dba/dba_driver.php(117): dba_mysql->connect('127.0.0.1', '0', 'blablanet7', 'mypassword...', 'blablanet.fr')    

#1 /var/www/domain/include/dba/dba_driver.php(41): dba_driver->__construct('127.0.0.1', '0', 'mysuser', 'mypassword...', domain', false)     
#2 /var/www/domain/include/cli_startup.php(25): dba_factory('127.0.0.1', '0', 'mysuser', 'mypassword...', 'domain', 0)      
#3 /var/www/domain/include/poller.php(9): cli_startup()     
#4 /var/www/domain/include/poller.php(443): poller_run(Array, 1)        
#5 {main}                 
  thrown in /var/www/domain/include/dba/dba_mysql.php on line 9      

```

**Comment by royalterra** [comment]
Close until further Investigation
