### ISSUE TITLE
Importing a channel fails: undefined function ref_session_write()

### ISSUE THREAD

**Issue by solstag** [redmatrix/hubzilla#383]
I have a recent installation and upon trying to import a channel I get:

`Fatal error: Uncaught Error: Call to undefined function ref_session_write() in /var/www/hubzilla/include/import.php:93 Stack trace: #0 /var/www/hubzilla/Zotlabs/Module/Import.php(137): import_channel(Array, 2, 0) #1 /var/www/hubzilla/Zotlabs/Module/Import.php(522): Zotlabs\Module\Import->import_account(2) #2 /var/www/hubzilla/Zotlabs/Web/Router.php(230): Zotlabs\Module\Import->post() #3 /var/www/hubzilla/index.php(155): Zotlabs\Web\Router->Dispatch(Object(miniApp)) #4 {main} thrown in /var/www/hubzilla/include/import.php on line 93`

Grepping the code, the referred function does seem to never get defined.

**Comment by solstag** [comment]
Thanks!
